-- First, remove the table if it exists
drop table if exists books;

-- Create the table anew
create table books (
  id INTEGER primary key generated by default as identity,
  book_name text,
  genre VARCHAR(30)
);

-- insert some test data
-- Using a multi-row insert statement here
insert into books (book_name, genre)
values
  ('HiHo', 'Drama'),
  ('Twilight', 'Fiction_Drama'),
  ('The office', 'comedy');